version: '3.8'  
  
services:  
  app:  
    image: mcr.microsoft.com/devcontainers/python:0-3.11  
    volumes:  
      - ..:/workspace:cached  
    command: sleep infinity  
    networks:  
      default:  
        aliases:  
          - localhost  
  
  redis:  
    image: redis/redis-stack:latest  
    ports:  
      - 6379:6379  
    networks:  
      default:  
        aliases:  
          - localhost  
  
networks:  
  default:  
