name: Build Version Bump

on:
  push:
    branches:
    - main

jobs:
  version_bump:
    name: Bump the build number
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
        token: ${{ secrets.CHIRPS_GITHUB_ACTION_PAT }}
    - name: Bump version
      uses: remorses/bump-version@js
      with:
          version_file: ./VERSION
      env:
          # Uses a personal access token (PAT) to bypass branch protection checks
          GITHUB_TOKEN: ${{ secrets.CHIRPS_GITHUB_ACTION_PAT }}
